spring:
  cloud:
    config:
      server:
        git:
          uri: https://github:com/313DEVGRP/Java-Service-Tree-Framework-Global-Config

arms:
  backend:
    url: http://backend-core:31313
  engine:
    url: http://engine-fire:33333
  local:
    url: http://127.0.0.1:33133

